{%- raw -%}
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  upload_assets:
    name: Create/Upload assets
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v3
      - name: Set up Python and PDM
        uses: pdm-project/setup-pdm@main
        with:
{%- endraw %}
          python-version: {{cookiecutter.min_supported_python}}
{%- raw %}
      - name: Install dependencies
        run: |
          pdm sync --dev --group docs
          pdm run build-docs
      - name: Publish
        run: pdm publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PWD }}
{%- endraw %}
