name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - "{{cookiecutter.__package_name}}/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "{{cookiecutter.__package_name}}/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
